name: eie_vision
channels:
  - defaults
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - scipy=1.2.0
  - pip
  - pip:
    - torch==1.4.0 # or 1.6.0
    - torchvision==0.5.0 # or 0.7.0
    - dominate
    - lpips
    - tensorboardX
    - tensorboard
    - crc32c
#    - mlflow>=1.0
#    - pytorch-lightning==0.8.3