model_params:
  name: 'BicycleGAN'
  in_channels: 3
  latent_dim: 256

exp_params:
  dataset: xBD
  img_size: 256 #64
  batch_size: 144 # Better to have a square number
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: [7]
  max_nb_epochs: 1 #100
  max_epochs: 1 #30

logging_params:
  save_dir: "experiments/"
  exp_name: "ExpBicycleGAN256" #Should it be the same as model_params name? "EIEExperiment" # bicycleGAN256_safegoal"
  manual_seed: 42

# logging_params:
#   save_dir: "logs/"
#   exp_name: "ExpBicycleGAN256"
#   manual_seed: 42

model_family_specific_params:  # TODO (Natalia): These should be integrated into other param fields above.
  MODEL: 'bicycle_gan'
  # dataset details
  CLASS: 'facades' #edges2shoes, day2night, edges2shoes, edges2handbags, maps, xBD_smalltiles, mini_pix2pix
  NZ: 8
  NO_FLIP: '--no_flip'
  DIRECTION: 'AtoB'
  LOAD_SIZE: 256
  CROP_SIZE: 256
  INPUT_NC: 1
  NITER: 1 #30
  NITER_DECAY: 0 #30
